/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.dao.ProdutoDAO;

/**
 *
 * @author marcal
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        txt_dscFind.setText("");

        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pnl_tela = new javax.swing.JPanel();
        pnl_menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_dscFind = new javax.swing.JTextField();
        btn_find = new javax.swing.JButton();
        btn_todos = new javax.swing.JButton();
        btn_att = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        pnl_conteudo = new javax.swing.JScrollPane();
        tbl_view = new javax.swing.JTable();
        menubar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jTextField4.setText("jTextField4");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Estoque");
        setMinimumSize(new java.awt.Dimension(900, 600));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        pnl_tela.setBackground(new java.awt.Color(153, 153, 255));

        pnl_menu.setBackground(new java.awt.Color(204, 204, 255));
        pnl_menu.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");

        txt_dscFind.setBackground(new java.awt.Color(153, 153, 255));
        txt_dscFind.setForeground(new java.awt.Color(255, 255, 255));
        txt_dscFind.setSelectionColor(new java.awt.Color(153, 204, 255));

        btn_find.setBackground(new java.awt.Color(153, 153, 255));
        btn_find.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_find.setForeground(new java.awt.Color(255, 255, 255));
        btn_find.setText("Pesquisar");
        btn_find.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_find.setBorderPainted(false);
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_todos.setBackground(new java.awt.Color(153, 153, 255));
        btn_todos.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_todos.setForeground(new java.awt.Color(255, 255, 255));
        btn_todos.setText("Todos");
        btn_todos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_todos.setBorderPainted(false);
        btn_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosActionPerformed(evt);
            }
        });

        btn_att.setBackground(new java.awt.Color(153, 153, 255));
        btn_att.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_att.setText("Atualizar");
        btn_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(153, 153, 255));
        btn_del.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_del.setForeground(new java.awt.Color(255, 255, 255));
        btn_del.setText("Excluir");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dscFind, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addComponent(btn_att, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(445, Short.MAX_VALUE))
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addComponent(btn_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_dscFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_att, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tbl_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Fornecedor", "Preço Origem", "Preço Final", "Qnt", "Limite Máx"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_view.setOpaque(false);
        pnl_conteudo.setViewportView(tbl_view);

        javax.swing.GroupLayout pnl_telaLayout = new javax.swing.GroupLayout(pnl_tela);
        pnl_tela.setLayout(pnl_telaLayout);
        pnl_telaLayout.setHorizontalGroup(
            pnl_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_telaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_conteudo))
                .addGap(15, 15, 15))
        );
        pnl_telaLayout.setVerticalGroup(
            pnl_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_telaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnl_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jMenu3.setText("Gerenciar");

        jMenuItem2.setText("Estoque");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cadastrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        menubar.add(jMenu3);

        jMenu4.setText("Config");

        jMenuItem4.setText("Opções de Estoque");
        jMenu4.add(jMenuItem4);

        menubar.add(jMenu4);

        jMenu1.setText("Sobre..");

        jMenuItem1.setText("Sobre..");
        jMenu1.add(jMenuItem1);

        menubar.add(jMenu1);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new TelaCadastro().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        readTableFind(txt_dscFind.getText());
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosActionPerformed
        // TODO add your handling code here:
        readTable();

    }//GEN-LAST:event_btn_todosActionPerformed

    private void btn_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attActionPerformed
        // TODO add your handling code here:
        if (tbl_view.getSelectedRow() != -1) {

            Produto p = new Produto();
            p.setId(Integer.parseInt(tbl_view.getValueAt(tbl_view.getSelectedRow(), 0).toString()));
            p.setDescricao(tbl_view.getValueAt(tbl_view.getSelectedRow(), 1).toString());
            p.setFornecedor(tbl_view.getValueAt(tbl_view.getSelectedRow(), 2).toString());
            p.setPrecoOrig(Float.parseFloat(tbl_view.getValueAt(tbl_view.getSelectedRow(), 3).toString()));
            p.setPrecoFin(Float.parseFloat(tbl_view.getValueAt(tbl_view.getSelectedRow(), 4).toString()));
            p.setQnt(Integer.parseInt(tbl_view.getValueAt(tbl_view.getSelectedRow(), 5).toString()));
            p.setLimite(Integer.parseInt(tbl_view.getValueAt(tbl_view.getSelectedRow(), 6).toString()));

            new TelaCadastro(p).setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione pelo menos um produto!");
        }


    }//GEN-LAST:event_btn_attActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        if (tbl_view.getSelectedRow() != -1) {

            if (JOptionPane.showConfirmDialog(null, "Deseja realmente apagar esse registro?", "Apagar produto selecionado", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                //JOptionPane.showMessageDialog(null, "clicou sim");
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();
                p.setId(Integer.parseInt(tbl_view.getValueAt(tbl_view.getSelectedRow(), 0).toString()));
                dao.delete(p);
                
            } else {
                JOptionPane.showMessageDialog(null, "Nada foi apagado!");

            }

        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        readTableFind(txt_dscFind.getText());
        
    }//GEN-LAST:event_btn_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public void readTable() {

        DefaultTableModel modelo = (DefaultTableModel) tbl_view.getModel();
        modelo.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();

        for (Produto p : dao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getFornecedor(),
                p.getPrecoOrig(),
                p.getPrecoFin(),
                p.getQnt(),
                p.getLimite()

            });

        }

    }
    public void readTableFind(String pFind) {

        DefaultTableModel modelo = (DefaultTableModel) tbl_view.getModel();
        modelo.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();

        for (Produto p : dao.readLike(pFind)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getFornecedor(),
                p.getPrecoOrig(),
                p.getPrecoFin(),
                p.getQnt(),
                p.getLimite()

            });

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_att;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_todos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JScrollPane pnl_conteudo;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_tela;
    private javax.swing.JTable tbl_view;
    private javax.swing.JTextField txt_dscFind;
    // End of variables declaration//GEN-END:variables
}
